import type { ServiceDefinition } from './types.ts';

export const serviceDefinitions: ServiceDefinition[] = [
  {
    key: 'aws',
    name: 'AWS',
    category: 'core-infra',
    statusUrl: 'https://health.aws.amazon.com/health/status',
    summaryUrl: 'https://status.aws.amazon.com/data.json',
    sourceKind: 'aws-health',
  },
  {
    key: 'google-cloud',
    name: 'Google Cloud',
    category: 'core-infra',
    statusUrl: 'https://status.cloud.google.com/?hl=ja',
    summaryUrl: 'https://status.cloud.google.com/incidents.json',
    sourceKind: 'google-cloud',
  },
  {
    key: 'github',
    name: 'GitHub',
    category: 'developer-platform',
    statusUrl: 'https://www.githubstatus.com',
    summaryUrl: 'https://www.githubstatus.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'anthropic',
    name: 'Anthropic',
    category: 'ai',
    statusUrl: 'https://status.anthropic.com',
    summaryUrl: 'https://status.anthropic.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'openai',
    name: 'OpenAI',
    category: 'ai',
    statusUrl: 'https://status.openai.com/',
    summaryUrl: 'https://status.openai.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'hashicorp',
    name: 'HashiCorp',
    category: 'core-infra',
    statusUrl: 'https://status.hashicorp.com',
    summaryUrl: 'https://status.hashicorp.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'docker',
    name: 'Docker',
    category: 'developer-platform',
    statusUrl: 'https://www.dockerstatus.com/',
    summaryUrl: 'https://www.dockerstatus.com/',
    sourceKind: 'docker-statusio',
  },
  {
    key: 'slack',
    name: 'Slack',
    category: 'work-collaboration',
    statusUrl: 'https://slack-status.com/',
    summaryUrl: 'https://slack-status.com/',
    sourceKind: 'slack-status',
  },
  {
    key: 'notion',
    name: 'Notion',
    category: 'work-collaboration',
    statusUrl: 'https://www.notion-status.com',
    summaryUrl: 'https://www.notion-status.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'pagerduty',
    name: 'PagerDuty',
    category: 'developer-platform',
    statusUrl: 'https://status.pagerduty.com/posts/dashboard',
    summaryUrl: 'https://status.pagerduty.com/posts/dashboard',
    sourceKind: 'pagerduty',
  },
  {
    key: 'sendgrid',
    name: 'SendGrid',
    category: 'developer-platform',
    statusUrl: 'https://status.sendgrid.com/',
    summaryUrl: 'https://status.sendgrid.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'zoom',
    name: 'Zoom',
    category: 'work-collaboration',
    statusUrl: 'https://www.zoomstatus.com/',
    summaryUrl: 'https://www.zoomstatus.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'bitwarden',
    name: 'Bitwarden',
    category: 'business-apps',
    statusUrl: 'https://status.bitwarden.com/',
    summaryUrl: 'https://status.bitwarden.com/',
    sourceKind: 'bitwarden-status',
  },
  {
    key: 'cloudflare',
    name: 'Cloudflare',
    category: 'core-infra',
    statusUrl: 'https://www.cloudflarestatus.com/',
    summaryUrl: 'https://www.cloudflarestatus.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'google-workspace',
    name: 'Google Workspace',
    category: 'work-collaboration',
    statusUrl: 'https://www.google.co.jp/appsstatus/dashboard/',
    summaryUrl: 'https://www.google.com/appsstatus/dashboard/incidents.json',
    sourceKind: 'google-workspace',
  },
  {
    key: 'microsoft365',
    name: 'Microsoft 365',
    category: 'work-collaboration',
    statusUrl:
      'https://status.cloud.microsoft/m365/referrer=serviceStatusRedirect',
    summaryUrl: 'https://status.cloud.microsoft/api/feed/mac',
    sourceKind: 'microsoft-feed',
  },
  {
    key: 'miro',
    name: 'Miro',
    category: 'work-collaboration',
    statusUrl: 'https://status.miro.com/',
    summaryUrl: 'https://status.miro.com/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'nodejs',
    name: 'Node.js',
    category: 'developer-platform',
    statusUrl: 'https://status.nodejs.org/',
    summaryUrl: 'https://status.nodejs.org/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'deno',
    name: 'Deno',
    category: 'developer-platform',
    statusUrl: 'https://denostatus.com/',
    summaryUrl: 'https://denostatus.com/api/v2/summary.json',
    sourceKind: 'simple-up-status',
  },
  {
    key: 'gather',
    name: 'Gather',
    category: 'work-collaboration',
    statusUrl: 'https://status.gather.town/',
    summaryUrl: 'https://status.gather.town/api/v2/summary.json',
    sourceKind: 'statuspage',
  },
  {
    key: 'money-forward',
    name: 'Money Forward',
    category: 'business-apps',
    statusUrl: 'https://status.i.moneyforward.com/',
    summaryUrl: 'https://status.i.moneyforward.com/',
    sourceKind: 'betterstack-status',
  },
  {
    key: 'magicpod',
    name: 'MagicPod',
    category: 'business-apps',
    statusUrl: 'https://status.magicpod.com/ja',
    summaryUrl: 'https://status.magicpod.com/ja',
    sourceKind: 'instatus-status',
  },
];
